-- Deploy iot_core:iot/mat_views/gateways_full_mat_view to pg


BEGIN;

CREATE MATERIALIZED VIEW IF NOT EXISTS iot.gateways_full_mat_view(
    id,
    gw_uuid,
    gw_uid,
    model,
    account_id,
    created,
    stats_last_seen,
    title,
    is_dev,
    send_fw_update,
    smarthome_last_seen,
    support_note,
    white_label_id,
    sysconfig,
    netconfig,
    last_lte_stats,
    last_lte_stats_time,
    parent_gw_uuid,
    uptime,
    max_pid,
    memfree,
    wan_mac,
    fw_version,
    xu_user,
    xu_version,
    load_average,
    fw_version_num,
    mesh_role,
    xu_hwlbl,
    xu_whitelabel,
    freedata,
    wifi_temp0,
    wifi_temp1,
    wifi_temp2,
    alerts_count,
    is_test_gw,
    provision_timestamp,
    srv_ott_enabled,
    srv_smarthome_enabled,
    srv_cs_enabled,
    srv_pc_enabled,
    dev_serial,
    net_topology_last_received,
    srv_smarthome_available,
    email,
    up_to_date,
    ott_serial,
    white_label)
AS
  SELECT gateways.id,
         gateways.gw_uuid,
         iot_convert_uuid_to_gw(gateways.gw_uuid) AS gw_uid,
         gateways.model,
         gateways.account_id,
         gateways.created,
         gateways.stats_last_seen,
         gateways.title,
         gateways.is_dev,
         gateways.send_fw_update,
         gateways.smarthome_last_seen,
         gateways.support_note,
         gateways.white_label_id,
         gateways.sysconfig,
         gateways.netconfig,
         gateways.last_lte_stats,
         gateways.last_lte_stats_time,
         gateways.parent_gw_uuid,
         gateways.uptime,
         gateways.max_pid,
         gateways.memfree,
         COALESCE(gateways.wan_mac::text, '00:00:00:00:00:00'::text) AS wan_mac,
         gateways.fw_version,
         gateways.xu_user,
         gateways.xu_version,
         gateways.load_average,
         gateways.fw_version_num,
         gateways.mesh_role,
         gateways.xu_hwlbl,
         gateways.xu_whitelabel,
         gateways.freedata,
         gateways.wifi_temp0,
         gateways.wifi_temp1,
         gateways.wifi_temp2,
         gateways.alerts_count,
         gateways.is_test_gw,
         gateways.provision_timestamp,
         gateways.srv_ott_enabled,
         gateways.srv_smarthome_enabled,
         gateways.srv_cs_enabled,
         gateways.srv_pc_enabled,
         COALESCE(gateways.dev_serial, ''::text) AS dev_serial,
         gateways.net_topology_last_received,
         gateways.srv_smarthome_available,
         COALESCE(uac.email, ''::character varying) AS email,
         CASE iot_get_update_url(gateways.gw_uuid) IS NULL
           WHEN true THEN true
           WHEN false THEN false
           ELSE false
         END AS up_to_date,
         COALESCE(dot.serial::text, ''::text) AS ott_serial,
         COALESCE(wl.white_label::text, ''::text) AS white_label
  FROM gateways
       LEFT JOIN user_accounts uac ON uac.id = gateways.account_id
       LEFT JOIN dev_ott dot ON gateways.gw_uuid = dot.gw_uuid
       LEFT JOIN white_labels wl ON gateways.white_label_id = wl.id;

COMMIT;
